### ISSUE TITLE
Commented Out?

### ISSUE THREAD

**Issue by jra2995** [gsdenys/kong-plugin-amqp#1]
https://github.com/gsdenys/kong-plugin-amqp/blob/afae97ce623daf51685d2f9cc9eedd47b0057584/kong/plugins/amqp/handler.lua#L66

I basically know zero lua, but I'm trying to use your plugin with kong gateway. Am I correct in seeing that the access method is commented out? Along with other plugin methods like init_worker? I don't want to be going crazy, but I'm trying to figure out why my plugin is not running.

**Comment by gsdenys** [comment]
sorry by delay, this plugins use some lua extensions, so, before run kong with this plugins you need to run luarocks install  kong-plugin-amqp-0.0.1-1.rockspec to download the dependencies

**Comment by gsdenys** [comment]
now there is how to install
